DATANAME="CESM"
START=200901
END=201312

LATNAME="lat"
LONNAME="lon"

# For each variable, specify level with unit (e.g. "850hPa", "85000Pa")
# Leave empty if single-level data

MSLP_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/PSL"
MSLP="PSL"
MSLP_LEVEL=""
MSLP_TRES="6h"
MSLP_UNIT="Pa"

Z850_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/Z3"
Z850="z850"
Z850_LEVEL=""
Z850_TRES="6h"
#"m2s-2" or "m"
Z850_UNIT="m" 

Z300_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/Z300"
Z300="z300"
Z300_LEVEL=""
Z300_TRES="6h"
#"m2s-2" or "m"
Z300_UNIT="m" 

Z500_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/Z500"
Z500="z500"
Z500_LEVEL=""
Z500_TRES="6h"
#"m2s-2" or "m"
Z500_UNIT="m" 


# If rv850 data do not exist, Fill u850 and v850
RV850_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/RV850"
RV850="rv850"
RV850_LEVEL=""
RV850_TRES="6h"
U850_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/U850"
U850="u850"
U850_LEVEL=""
U850_TRES="6h"
V850_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/V850"
V850="v850"
V850_LEVEL=""
V850_TRES="6h"

R850_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/RELHUM"
R850="rh850"
R850_LEVEL=""
R850_TRES="6h"
# "fraction" or "%"
R850_UNIT="%" 

U10_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/U10"
U10="U10"
U10_LEVEL=""
U10_TRES="6h"

V10_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/VBOT"
V10="VBOT"
V10_LEVEL=""
V10_TRES="6h"

ZS_DIR="/home/disk/eos4/moon/seed/data/timeslice/extract/PHIS"
ZS="PHIS"
ZS_LEVEL=""
ZS_TRES="6h"
# "m" or "m2s-2"
ZS_UNIT="m" 

RH_THRESHOLD=75.0
